### PR TITLE
hack - manually set build to pass prerelease version to nuget pack

### PR DESCRIPTION
**Pull request by thirkcircus**
i need to work out how to change the build number passed in by appveyor - but in the meantime, hacking the build number to prerelease in the build script so it can nuget pack...

### CODE REVIEW

**Comment by merbla** [comment]
@thirkcircus AppVeyor sets the build number.  Did you want to bump it up?

image

image

**Comment by thirkcircus** [comment]
yes please.  1.1 would do.
is there any way to set this myself or do i contact you everytime we want
to bump the version?

also regardless, I'm still not sure how to set the build with a prerelease
version.  Normally I use gitversion to handle versioning for me but I don't
want to go around changing the whole build pipeline process...  ;)

because I'm relying on an awssdk prerelease version, i also need to publish
a prerelease version of the serilog sink...  not sure of the best way to do
this.  hacking the build script was just a temp workaround.

happy to do whatever, just need a steer in the right direction. :)

On 26 June 2015 at 14:21, Matthew Erbs <notifications@github.com> wrote:

> @thirkcircus <https://github.com/thirkcircus> AppVeyor sets the build
> number. Did you want to bump it up?
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/637298/8369490/c8cba476-1bfd-11e5-9bc5-342787eefb58.png>
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/637298/8369495/e9757b52-1bfd-11e5-9593-f75353a5487c.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/serilog/serilog-sinks-amazonkinesis/pull/8#issuecomment-115464980>
> .
>



-- 

Justin Thirkell

Senior Developer

Mobile +64 21 474 752

3 Market Lane, Wellington, 6142, New Zealand, PO Box 24 537

Xero - Beautiful accounting software

**Comment by merbla** [comment]
so its more of an alpha/beta NuGet package?

**Comment by nblumhardt** [comment]
(Following up on an offline chat with Justin:)

I think Serilog.Sinks.Literate's Build.ps1 covers it:

https://github.com/serilog/serilog-sinks-literate/blob/dev/Build.ps1#L59

The script needs a bit of love in that the parameter names don't exactly match their purpose anymore, but the way "branch" is handled will cover what you need, and then the dev branch will build -pre and master will build others. Ideally we'd publish the -pre builds to a MyGet feed somewhere...

This repo probably needs a dev branch added for this to work (good idea to set the default branch to dev in settings once that's done).

HTH!

**Comment by thirkcircus** [comment]
ok, thanks, understand.  i'll branch to develop.

last question - how is the build number controlled by appveyor?  Is this something I can bump or is there a separate admin for appveyor? (and if so how/where do i ask, when I want version numbers adjusted?)  
cheers

**Comment by nblumhardt** [comment]
In the case of the literate sink linked above, it is controlled by CHANGES.md - the build number is taken to be the first line in the file. To get this working, some AppVeyor settings need to be tweaked; let me know if/when you need this, I can sort it out.

**Pull request merged**
