### PR TITLE
Added support for async methods, netstandard2.0, netstandard1.6

### PR DESCRIPTION
**Pull request by troylar**

### CODE REVIEW

**Comment by jakejscott** [comment]
This still needs to support net45

**Comment by jakejscott** [comment]
Also you should just use `GetAwaiter().GetResult()` instead of `.Result` as it avoids wrapping any exceptions in an `AggregateException`.

````csharp

_kinesisFirehoseClient.PutRecordBatchAsync(request)).GetAwaiter().GetResult()

````

instead of

````csharp

var putRecordBatchTask  =  Task.Run(async () => await _kinesisFirehoseClient.PutRecordBatchAsync(request));

var result = putRecordBatchTask.Result;

````

You can read more about this here:
- http://blog.stephencleary.com/2014/12/a-tour-of-task-part-6-results.html
- https://blogs.msdn.microsoft.com/pfxteam/2011/09/28/task-exception-handling-in-net-4-5/
- https://github.com/aspnet/Security/issues/59

**Comment by Ry-K** [comment]
Wouldn't you just target netstandard2.0 only? That is compatible with .NET core & full framework.

**Comment by troylar** [comment]
@Ry-K netstandard2.0 only supports back to 4.6.1 

https://github.com/dotnet/standard/blob/master/docs/versions.md

**Comment by troylar** [comment]
@jakejscott @Ry-K I changed targeting to net45 and netstandard2.0, which should support everything going back to 4.5.

**Comment by wcrooy** [comment]
@jakejscott @Ry-K Can you start merging this. If not what's missing? Perhaps I can help out. Because I also need the .net core changes.

**Comment by wcrooy** [comment]
@troylar 
I noticed that the assembly name was renamed from Serilog.Sinks.Amazon.Kinesis
to Serilog.Sinks.AmazonKinesis. 

Any good reason for that?

**Comment by troylar** [comment]
@jakejscott @Ry-K Can you take rev

**Comment by wcrooy** [comment]
@thirkcircus Plz have look and merge this. If something else needs to be done let me/us know.

**Comment by troylar** [comment]
@wcrooy Thanks for your fixes!

**Comment by troylar** [comment]
@wcrooy it's merged

**Pull request merged**
