### PR TITLE
prevent bookmark file locking throwing exceptions

### PR DESCRIPTION
**Pull request by thirkcircus**
currently both firehose and stream logshippers have the same logger name... :grimacing:

### CODE REVIEW

**Comment by thirkcircus** [comment]
the serilog seq sink has this;
```cs
try {
	 File.Open (bookmark, etc)
}
catch (Exception ex){
	SelfLog.WriteLine("Exception while emitting periodic batch from {0}: {1}", this, ex);
}
```

we mistakenly treated all such exceptions as meaningful and propagated these to consumers like so;
```cs
try {
	 File.Open (bookmark, etc)
}
catch (Exception ex){
	Logger.DebugException("Exception while emitting periodic batch", ex);
	OnLogSendError(new LogSendErrorEventArgs(string.Format("Error in shipping logs to '{0}' stream)", _streamName), ex));
}
```

turns out that in our IIS app there were many many bookmark file lock exceptions being thrown (thousands/minute).
locally it was simple to repro too, seeing two threads, one succeeding in opening/locking the bookmark, the other thread throwing.

this PR applies the same forgiving stance towards filelock exceptions as seen for the log file code directly below in the same file.

it is unclear whether swallowing so many exceptions will cause meaningful overhead when operating at scale, but this fix will at least alleviate the immediate problem.

@endofcake

**Comment by thirkcircus** [comment]
@endofcake , please review PR at some point but i'm going to merge now in order to push fixes to downstream consumer...

**Comment by endofcake** [comment]
Not entirely clear here - I was thinking that we were capturing IOExceptions just before this catch-all `catch (Exception ex)` and swallowing them. Did we miss some?

**Comment by endofcake** [comment]
Would probably be nice to extract this into a method:
```
#if NET40
                long win32ErrorCode = System.Runtime.InteropServices.Marshal.GetHRForException(ex) & 0xFFFF;
#else
                long win32ErrorCode = ex.HResult & 0xFFFF;
#endif
```
Would help readability and hide compile directives somewhat.

**Pull request merged**
