### PR TITLE
Updated solution for using .NET 4.5 and Serilog 2.x

### PR DESCRIPTION
**Pull request by ahydrax**
Hello there,

This package can be used now with Serilog 2.x versions.

### CODE REVIEW

**Comment by endofcake** [comment]
This looks good to me.
@thirkcircus , ok to merge?

**Comment by thirkcircus** [comment]
@ahydrax , we originally had this targeting net40 due to a downstream consumer (that we also own).
is there a particular need to target net45?  is that the min framework version supported by serilog 2x?

**Comment by ahydrax** [comment]
@thirkcircus , as I can see [here](https://www.nuget.org/packages/Serilog/2.0.0) it's a minimum required version.

**Comment by thirkcircus** [comment]
fair enough then.  :smile:
thanks!

**Comment by esukirno** [comment]
Hi @thirkcircus @ahydrax. I still cannot find nuget package for this sink with serilog 2.x.x dependency.
Did this PR build artifact get pushed to nuget.org?

**Comment by ahydrax** [comment]
@esukirno seems not. @thirkcircus do you have an access to nuget package management?

**Comment by thirkcircus** [comment]
Sorry, I don't.
It's been a long time since I looked at this project and I was thinking that I must have a build pipeline somewhere but I've just checked nuget.org and this package isn't listed under my name, so it can't have been me who pushed it.  @nblumhardt might know about any build pipeline...

**Comment by nblumhardt** [comment]
Hi folks,

Indeed it does! :-) .. The build pipeline's linked from the README: https://ci.appveyor.com/project/serilog/serilog-sinks-amazonkinesis/branch/master

The latest build completed with the following:

```
Collecting artifacts...
Found artifact 'Serilog.Sinks.AmazonKinesis.2.0.99.nupkg' matching 'Serilog.*.nupkg' path
Uploading artifacts...
[1/1] Serilog.Sinks.AmazonKinesis.2.0.99.nupkg (67,319 bytes)...100%
"NuGet" deployment has been skipped as environment variable has not matched ("appveyor_repo_tag" is "false", should be "true")
Build success
```

The YML build configuration exported from AppVeyor is:

```yml
version: '{build}'
build_script:
- ps: >-
    $version = $env:APPVEYOR_REPO_TAG_NAME

    if (-not $version) {

    $version = "2.0"

    }

    ./Build.ps1 -majorMinor "$version" -patch "$env:APPVEYOR_BUILD_VERSION" -customLogger "C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
artifacts:
- path: Serilog.*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: nvZ/z+pMS91b3kG4DgfES5AcmwwGoBYQxr9kp4XiJHj25SAlgdIxFx++1N0lFH2x
  on:
    branch: master
    appveyor_repo_tag: true
```

I'll remove the last line and check this into _master_ - should get things unblocked. (Ideally we'e move the project to the new build scripts in line with the other Serilog sinks at some point.)

**Comment by nblumhardt** [comment]
Ready to go: https://www.nuget.org/packages/Serilog.Sinks.AmazonKinesis/2.2.102

**Comment by ahydrax** [comment]
@nblumhardt thanks!

**Pull request merged**
